name: Python Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут кода
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Установка Allure вручную
      - name: Install Allure
        run: |
          # Скачиваем последнюю версию Allure
          curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          # Распаковываем
          sudo unzip allure-commandline.zip -d /usr/local/bin/
          # Делаем бинарный файл исполняемым
          sudo chmod +x /usr/local/bin/allure-2.29.0/bin/allure
          # Проверяем версию
          /usr/local/bin/allure-2.29.0/bin/allure --version
          # Добавляем путь в PATH
          echo "PATH=$PATH:/usr/local/bin/allure-2.29.0/bin" >> $GITHUB_ENV

      # 5. Запуск тестов с генерацией Allure-результатов
      - name: Run tests
        run: |
          pytest --alluredir=./allure-results tests/ || true

      # 6. Получение истории Allure (если есть)
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 7. Генерация Allure-отчета
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./allure-results -o ./allure-report --clean
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history ./allure-report/history
          fi

      # 8. Публикация отчета на GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false

      # 9. Вывод ссылки на отчет
      - name: Print Allure Report URL
        if: always()
        run: |
          echo "Allure Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
